export const characters = new Map([
  [
    "zhongli",
    {
      name: "Zhongli",
      description:
        "A mysterious expert contracted by the Wangsheng Funeral Parlor. Extremely knowledgeable in all things.",
      emoji: "<:zhongli:843214509605650442>",
      thumbnail: "https://i.imgur.com/FbpPr3j.png",
      image: "https://i.imgur.com/FbpPr3j.png",
      color: "ffc100",
      category: "Geo",
      rarity: "⭐⭐⭐⭐⭐",
      element: "<:Geo:798483630740865044> Geo",
      weapon: "Polearm",
      nation: "Liyue",
      affiliation: "Wangsheng Funeral Parlor Archons",
      specialDish: "Slow-Cooked Bamboo Shoot Soup",
      constellation: "Lapis Dei",
      birthday: "December 31st",
      ascensionCost: "https://i.imgur.com/LPvxOnj.png",
      talentCost: "https://i.imgur.com/BIN4nWN.png",
      const: "https://i.imgur.com/z0HicE0.png",
      talents: "https://i.imgur.com/ON3RMuI.png",
      passive: "https://i.imgur.com/xyp2DWE.png",
    },
  ],
  [
    "xinyan",
    {
      name: "Xinyan",
      description:
        "Liyue's sole rock 'n' roll musician. She rebels against ossified prejudices using her music and passionate singing.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/c/c8/Character_Xinyan_Portrait.png/revision/latest?cb=20201128161608",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/c/c8/Character_Xinyan_Portrait.png/revision/latest?cb=20201128161608",
      color: "ff4000",
      emoji: "<:xinyan:843214509609844796>",
      category: "Pyro",
      rarity: "⭐⭐⭐⭐",
      element: "<:Pyro:798483485832249354> Pyro",
      weapon: "Claymore",
      nation: "Liyue",
      affiliation: "Liyue Harbor",
      specialDish: "Rockin' Riffin' Chicken!",
      constellation: "Fila Ignium",
      birthday: "October 16th",
      ascensionCost: "https://i.imgur.com/2GtaTup.png",
      talentCost: "https://i.imgur.com/fH5WwHO.png",
      const: "https://i.imgur.com/E1rh1Yh.png",
      talents: "https://i.imgur.com/uFT2i8l.png",
      passive: "https://i.imgur.com/y82XJnd.png",
    },
  ],
  [
    "xingqiu",
    {
      name: "Xingqiu",
      description:
        "He is the second son of the Guild Manager of the Feiyun Commerce Guild, an influential group in Liyue, and is also a self-proclaimed practitioner of the Guhua Clan's arts.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/a/a9/Character_Xingqiu_Portrait.png/revision/latest/?cb=20200916184107",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/a/a9/Character_Xingqiu_Portrait.png/revision/latest/?cb=20200916184107",
      color: "0379fd",
      emoji: "<:xingqiu:843214509489127445>",
      category: "Hydro",
      rarity: "⭐⭐⭐⭐",
      element: "<:Hydro:798483587157983282> Hydro",
      weapon: "Sword",
      nation: "Liyue",
      affiliation: "Feiyun Commerce Guild",
      specialDish: "All-Delicacy Parcels",
      constellation: "Fabulae Textile",
      birthday: "October 9th",
      ascensionCost: "https://i.imgur.com/BgTSS8x.png",
      talentCost: "https://i.imgur.com/xcGFi8D.png",
      const: "https://i.imgur.com/NLBPbc8.png",
      talents: "https://i.imgur.com/q9uakg5.png",
      passive: "https://i.imgur.com/XWa52RN.png",
    },
  ],
  [
    "xiangling",
    {
      name: "Xiangling",
      description:
        "A renowned chef from Liyue. She's extremely passionate about cooking and excels at making her signature hot and spicy dishes.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/2/22/Character_Xiangling_Portrait.png/revision/latest/scale-to-width-down/310?cb=20200916184026",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/2/22/Character_Xiangling_Portrait.png/revision/latest/scale-to-width-down/310?cb=20200916184026",
      color: "ff4000",
      emoji: "<:xiangling:843214509643923496>",
      category: "Pyro",
      rarity: "⭐⭐⭐⭐",
      element: "<:Pyro:798483485832249354> Pyro",
      weapon: "Polearm",
      nation: "Liyue",
      affiliation: "Wanmin Restaurant",
      specialDish: "Wanmin Restaurant's Boiled Fish",
      constellation: "Trulla",
      birthday: "November 2nd",
      ascensionCost: "https://i.imgur.com/84nW7Uo.png",
      talentCost: "https://i.imgur.com/aCYggGD.png",
      const: "https://i.imgur.com/fXGipqw.png",
      talents: "https://i.imgur.com/bFGDa45.png",
      passive: "https://i.imgur.com/gGYZlCE.png",
    },
  ],
  [
    "venti",
    {
      name: "Venti",
      description:
        "Venti is the wine-loving bard in Mondstadt who will share you his stories and maybe even sing for you, if you buy him some wine.\nIt appears there is more than meets the eye to the half-witted bard. ",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/c/cf/Character_Venti_Portrait.png/revision/latest/?cb=20200916184309",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/c/cf/Character_Venti_Portrait.png/revision/latest/?cb=20200916184309",
      color: "03fd9e",
      emoji: "<:venti:843214509615480842>",
      category: "Anemo",
      rarity: "⭐⭐⭐⭐⭐",
      element: "<:Anemo:798483595781341194> Anemo",
      weapon: "Bow",
      nation: "Mondstadt",
      affiliation: "Archons",
      specialDish: "A Buoyant Breeze",
      constellation: "Carmen Dei",
      birthday: "June 16th",
      ascensionCost: "https://i.imgur.com/EXu8waa.png",
      talentCost: "https://i.imgur.com/6r829rg.png",
      const: "https://i.imgur.com/0RzUEdJ.png",
      talents: "https://i.imgur.com/lIDG8hA.png",
      passive: "https://i.imgur.com/8GA1aA6.png",
    },
  ],
  [
    "sucrose",
    {
      name: "Sucrose",
      description:
        "An alchemist filled with curiosity about all things. She researches bio-alchemy.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/2/20/Character_Sucrose_Portrait.png/revision/latest/scale-to-width-down/244?cb=20200916181011",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/2/20/Character_Sucrose_Portrait.png/revision/latest/scale-to-width-down/244?cb=20200916181011",
      color: "03fd9e",
      emoji: "<:sucrose:843214509534347285>",
      category: "Anemo",
      rarity: "⭐⭐⭐⭐",
      element: "<:Anemo:798483595781341194> Anemo",
      weapon: "Catalyst",
      nation: "Mondstadt",
      affiliation: "Knights of Favonius",
      specialDish: "Nutritious Meal (V. 593)",
      constellation: "Ampulla",
      birthday: "November 26th",
      ascensionCost: "https://i.imgur.com/6rnsoNC.png",
      talentCost: "https://i.imgur.com/8jdr3vl.png",
      const: "https://i.imgur.com/ykAJ3uz.png",
      talents: "https://i.imgur.com/QEU2vrH.png",
      passive: "https://i.imgur.com/OhiNHX7.png",
    },
  ],
  [
    "razor",
    {
      name: "Razor",
      description:
        "Abandoned as an infant, Razor was taken in by the Wolf of the North, Andrius, and raised by his wolf pack in Wolvendom.\nAfter a chance encounter with the Knights of Favonius' Grand Master, Varka, he has slowly started integrating with humans again.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/1/1e/Character_Razor_Portrait.png/revision/latest/cb=20200916151017",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/1/1e/Character_Razor_Portrait.png/revision/latest/cb=20200916151017",
      color: "e205fd",
      emoji: "<:razor:843215534711242813>",
      category: "Electro",
      rarity: "⭐⭐⭐⭐",
      element: "<:Electro:798483560205385799> Electro",
      weapon: "Claymore",
      nation: "Mondstadt",
      affiliation: "Wolvendom (Andrius)",
      specialDish: "Puppy-Paw Hash Brown",
      constellation: "Lupus Minor",
      birthday: "September 9th",
      ascensionCost: "https://i.imgur.com/oW57fzV.png",
      talentCost: "https://i.imgur.com/fGu99SV.png",
      const: "https://i.imgur.com/XcbXoPs.png",
      talents: "https://i.imgur.com/IyrYK4l.png",
      passive: "https://i.imgur.com/chqBqaS.png",
    },
  ],
  [
    "qiqi",
    {
      name: "Qiqi",
      description:
        "Resurrected as a zombie by the adepti, she has ended up in Baizhu's care and now works at Bubu Pharmacy in Liyue Harbor.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/2/2a/Character_Qiqi_Portrait.png/revision/latest/scale-to-width-down/310?cb=20200916183756",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/2/2a/Character_Qiqi_Portrait.png/revision/latest/scale-to-width-down/310?cb=20200916183756",
      color: "00f9ff",
      emoji: "<:qiqi:843214509463175229>",
      category: "Cryo",
      rarity: "⭐⭐⭐⭐⭐",
      element: "<:Cryo:798578651145830401> Cryo",
      weapon: "Sword",
      nation: "Liyue",
      affiliation: "Bubu Pharmacy",
      specialDish: "No Tomorrow",
      constellation: "Pristina Nola",
      birthday: "March 3rd",
      ascensionCost: "https://i.imgur.com/D0uZiME.png",
      talentCost: "https://i.imgur.com/tpKFAHc.png",
      const: "https://i.imgur.com/XfpyXQg.png",
      talents: "https://i.imgur.com/xKKe5G1.png",
      passive: "https://i.imgur.com/SVgTMWp.png",
    },
  ],
  [
    "noelle",
    {
      name: "Noelle",
      description:
        "While not yet a knight, she seeks to one day join the Knights of Favonius by first serving as a dutiful maid.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/a/a5/Character_Noelle_Portrait.png/revision/latest/scale-to-width-down/247?cb=20200916183843",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/a/a5/Character_Noelle_Portrait.png/revision/latest/scale-to-width-down/247?cb=20200916183843",
      color: "ffc100",
      emoji: "<:noelle:843214509380599850>",
      category: "Geo",
      rarity: "⭐⭐⭐⭐",
      element: "<:Geo:798483630740865044> Geo",
      weapon: "Claymore",
      nation: "Mondstadt",
      affiliation: "Knights of Favonius",
      specialDish: "Lighter-Than-Air Pancake",
      constellation: "Parma Cordis",
      birthday: "March 21st",
      ascensionCost: "https://i.imgur.com/zY2LUHW.png",
      talentCost: "https://i.imgur.com/VvGV1sp.png",
      const: "https://i.imgur.com/Ccn8JqX.png",
      talents: "https://i.imgur.com/xoPxOVb.png",
      passive: "https://i.imgur.com/vyQaNIG.png",
    },
  ],
  [
    "ningguang",
    {
      name: "Ningguang",
      emoji: "<:ningguang:843214509606961272>",
      category: "Geo",
      description:
        "The Tianquan of Liyue Qixing. Her wealth is unsurpassed in all of Teyvat.",
      thumbnail:
        "https://cdn.discordapp.com/attachments/798854249806037033/813056148856111164/usy9I7B.png",
      image:
        "https://cdn.discordapp.com/attachments/798854249806037033/813056148856111164/usy9I7B.png",
      color: "ffc100",
      rarity: "⭐⭐⭐⭐",
      element: "<:Geo:798483630740865044> Geo",
      weapon: "Catalyst",
      nation: "Liyue",
      affiliation: "Liyue Qixing",
      specialDish: "Qiankun Mora Meat",
      constellation: "Opus Aqe",
      birthday: "August 26th",
      ascensionCost: "https://i.imgur.com/Zp590eo.png",
      talentCost: "https://i.imgur.com/UqwY67o.png",
      const: "https://i.imgur.com/00GYNTa.png",
      talents: "https://i.imgur.com/EgxCb04.png",
      passive: "https://i.imgur.com/5R9Zlm7.png",
    },
  ],
  [
    "lisa",
    {
      name: "Lisa",
      description:
        "The languid but knowledgeable Librarian of the Knights of Favonius, deemed by Sumeru Academia to be their most distinguished graduate in the past two centuries.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/f/fa/Character_Lisa_Portrait.png/revision/latest/scale-to-width-down/251?cb=20200916171314",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/f/fa/Character_Lisa_Portrait.png/revision/latest/scale-to-width-down/251?cb=20200916171314",
      color: "e205fd",
      emoji: "<:lisa:843214509706444840>",
      category: "Electro",
      rarity: "⭐⭐⭐⭐",
      element: "<:Electro:798483560205385799> Electro",
      weapon: "Catalyst",
      nation: "Mondstadt",
      affiliation: "Knights of Favonius",
      specialDish: "Mysterious Bolognese",
      constellation: "Tempus Fugit",
      birthday: "June 9th",
      ascensionCost: "https://i.imgur.com/cJ1TMla.png",
      talentCost: "https://i.imgur.com/uAF0JnO.png",
      const: "https://i.imgur.com/VXeGSsZ.png",
      talents: "https://i.imgur.com/yuSakFs.png",
      passive: "https://i.imgur.com/SngMvQo.png",
    },
  ],
  [
    "klee",
    {
      name: "Klee",
      description:
        "The daughter of the intrepid — and destructive — adventurer Alice, Klee takes her mother in many ways, much to the consternation of the Knights of Favonius whom she has been entrusted to.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/3/3f/Character_Klee_Portrait.png/revision/latest/scale-to-width-down/267?cb=20200916171245",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/3/3f/Character_Klee_Portrait.png/revision/latest/scale-to-width-down/267?cb=20200916171245",
      color: "ff4000",
      emoji: "<:klee:843214509393182731>",
      category: "Pyro",
      rarity: "⭐⭐⭐⭐⭐",
      element: "<:Pyro:798483485832249354> Pyro",
      weapon: "Catalyst",
      nation: "Mondstadt",
      affiliation: "Knights of Favonius",
      specialDish: "Fish-Flavored Toast",
      constellation: "Trifolium",
      birthday: "July 27th",
      ascensionCost: "https://i.imgur.com/0FQi1vY.png",
      talentCost: "https://i.imgur.com/g0MunBH.png",
      const: "https://i.imgur.com/LOgMJ68.png",
      talents: "https://i.imgur.com/yWi2Mgu.png",
      passive: "https://i.imgur.com/FatlZyc.png",
    },
  ],
  [
    "keqing",
    {
      name: "Keqing",
      description:
        "The Yuheng of the Liyue Qixing. Keqing has much to say about Rex Lapis' unilateral approach to policymaking in Liyue — but in truth, gods admire skeptics such as her quite a lot.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/8/81/Character_Keqing_Portrait.png/revision/latest/scale-to-width-down/310?cb=20200916184644",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/8/81/Character_Keqing_Portrait.png/revision/latest/scale-to-width-down/310?cb=20200916184644",
      color: "e205fd",
      emoji: "<:keqing:843214509719420928>",
      category: "Electro",
      rarity: "⭐⭐⭐⭐⭐",
      element: "<:Electro:798483560205385799> Electro",
      weapon: "Sword",
      nation: "Liyue",
      affiliation: "Liyue Qixing",
      specialDish: "Survival Grilled Fish",
      constellation: "Trulla Cementarii",
      birthday: "November 20th",
      ascensionCost: "https://i.imgur.com/jQ2kJyI.png",
      talentCost: "https://i.imgur.com/x7RbcOY.png",
      const: "https://i.imgur.com/WWUAzbg.png",
      talents: "https://i.imgur.com/mh71EzE.png",
      passive: "https://i.imgur.com/LFJZvTg.png",
    },
  ],
  [
    "kaeya",
    {
      name: "Kaeya",
      description:
        "A thinker in the Knights of Favonius with a somewhat exotic appearance.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/1/1c/Character_Kaeya_Portrait.png/revision/latest/scale-to-width-down/310?cb=20200916171117",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/1/1c/Character_Kaeya_Portrait.png/revision/latest/scale-to-width-down/310?cb=20200916171117",
      color: "00f9ff",
      emoji: "<:kaeya:843214509606567936>",
      category: "Cryo",
      rarity: "⭐⭐⭐⭐",
      element: "<:Cryo:798483525052530719> Cryo",
      weapon: "Sword",
      nation: "Mondstadt",
      affiliation: "Knights of Favonius",
      specialDish: "Fruity Skewers",
      constellation: "Pavo Ocellus",
      birthday: "November 30th",
      ascensionCost: "https://i.imgur.com/QwMEn4P.png",
      talentCost: "https://i.imgur.com/BahvWdc.png",
      const: "https://i.imgur.com/XqEQe1Q.png",
      talents: "https://i.imgur.com/YsLXzXf.png",
      passive: "https://i.imgur.com/qy7DonJ.png",
    },
  ],
  [
    "jean",
    {
      name: "Jean",
      description:
        "The righteous and rigorous Dandelion Knight, and Acting Grand Master of Mondstadt's Knights of Favonius.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/0/02/Character_Jean_Portrait.png/revision/latest/scale-to-width-down/310?cb=20200916180808",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/0/02/Character_Jean_Portrait.png/revision/latest/scale-to-width-down/310?cb=20200916180808",
      color: "03fd9e",
      emoji: "<:jean:843214509283868724>",
      category: "Anemo",
      rarity: "⭐⭐⭐⭐⭐",
      element: "<:Anemo:798483595781341194> Anemo",
      weapon: "Sword",
      nation: "Mondstadt",
      affiliation: "Knights of Favonius",
      specialDish: "Invigorating Pizza",
      constellation: "Leo Minor",
      birthday: "March 14th",
      ascensionCost: "https://i.imgur.com/mrjkdAi.png",
      talentCost: "https://i.imgur.com/ZHRSCSf.png",
      const: "https://i.imgur.com/QXBOITz.png",
      talents: "https://i.imgur.com/GueuW0g.png",
      passive: "https://i.imgur.com/EsBXj0S.png",
    },
  ],
  [
    "ganyu",
    {
      name: "Ganyu",
      description:
        "The secretary at Yuehai Pavilion. The blood of the qilin, an illuminated beast, flows within her veins.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/a/a0/Character_Ganyu_Portrait.png/revision/latest/scale-to-width-down/246?cb=20210109020221",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/a/a0/Character_Ganyu_Portrait.png/revision/latest/scale-to-width-down/246?cb=20210109020221",
      color: "00f9ff",
      emoji: "<:ganyu:843215307745394728>",
      category: "Cryo",
      rarity: "⭐⭐⭐⭐⭐",
      element: "<:Cryo:798483525052530719> Cryo",
      weapon: "Bow",
      nation: "Liyue",
      affiliation: "Yuehai Pavilion",
      specialDish: "Prosperous Peace",
      constellation: "Sinae Unicornis",
      birthday: "December 2nd",
      ascensionCost: "https://i.imgur.com/nL1vU54.png",
      talentCost: "https://i.imgur.com/CVRQXFa.png",
      const: "https://i.imgur.com/vIlonqd.png",
      talents: "https://i.imgur.com/fNtEGMr.png",
      passive: "https://i.imgur.com/hwX4tzB.png",
    },
  ],
  [
    "fischl",
    {
      name: "Fischl",
      description:
        "A mysterious girl who calls herself 'Prinzessin der Verurteilung' and travels with a night raven named Oz.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/3/34/Character_Fischl_Portrait.png/revision/latest/scale-to-width-down/282?cb=20200916171212",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/3/34/Character_Fischl_Portrait.png/revision/latest/scale-to-width-down/282?cb=20200916171212",
      color: "e205fd",
      emoji: "<:fischl:843214510005551105>",
      category: "Electro",
      rarity: "⭐⭐⭐⭐",
      element: "<:Electro:798483560205385799> Electro",
      weapon: "Bow",
      nation: "Mondstadt",
      affiliation: "Adventurers' Guild",
      specialDish: "Die Heilige Sinfonie",
      constellation: "Corvus",
      birthday: "May 27th",
      ascensionCost: "https://i.imgur.com/YgOEn3a.png",
      talentCost: "https://i.imgur.com/E3SMdrn.png",
      const: "https://i.imgur.com/GihZrjN.png",
      talents: "https://i.imgur.com/YdLLJr5.png",
      passive: "https://i.imgur.com/B80KFaN.png",
    },
  ],
  [
    "diluc",
    {
      name: "Diluc",
      description:
        "Born into the affluent Ragnvindr Family, Diluc is the current owner of the Dawn Winery and a nobleman of high esteem in Mondstadt society.\nWhile a past incident caused him to split ways with the Knights of Favonius, he continues to protect Mondstadt in his own way. ",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/b/bc/Character_Diluc_Portrait.png/revision/latest/scale-to-width-down/228?cb=20200916171027",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/b/bc/Character_Diluc_Portrait.png/revision/latest/scale-to-width-down/228?cb=20200916171027",
      color: "ff4000",
      emoji: "<:diluc:843214508956713000>",
      category: "Pyro",
      rarity: "⭐⭐⭐⭐⭐",
      element: "<:Pyro:798483485832249354> Pyro",
      weapon: "Claymore",
      nation: "Mondstadt",
      affiliation: "Dawn Winery\nKnights of Favonius (Formerly)",
      specialDish: "Once Upon a Time in Mondstadt",
      constellation: "Noctua",
      birthday: "April 30th",
      ascensionCost: "https://i.imgur.com/C0cFjTj.png",
      talentCost: "https://i.imgur.com/0onrtYW.png",
      const: "https://i.imgur.com/AP3lefG.png",
      talents: "https://i.imgur.com/aI5FFgZ.png",
      passive: "https://i.imgur.com/uK3BahT.png",
    },
  ],
  [
    "chongyun",
    {
      name: "Chongyun",
      description:
        "A young exorcist from a family of exorcists. He does everything he can to suppress his pure positive energy.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/a/aa/Character_Chongyun_Portrait.png/revision/latest/scale-to-width-down/250?cb=20200916181119",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/a/aa/Character_Chongyun_Portrait.png/revision/latest/scale-to-width-down/250?cb=20200916181119",
      color: "00f9ff",
      emoji: "<:chongyun:843214508876496917>",
      category: "Cryo",
      rarity: "⭐⭐⭐⭐",
      element: "<:Cryo:798483525052530719> Cryo",
      weapon: "Claymore",
      nation: "Liyue",
      affiliation: "None",
      specialDish: "Cold Noodles with Mountain Delicacies",
      constellation: "Nubis Caesor",
      birthday: "September 7th",
      ascensionCost: "https://i.imgur.com/2zE4uzT.png",
      talentCost: "https://i.imgur.com/9aVkSPt.png",
      const: "https://i.imgur.com/KoSxPe2.png",
      talents: "https://i.imgur.com/if9AGj5.png",
      passive: "https://i.imgur.com/HKFK1dA.png",
    },
  ],
  [
    "tartaglia",
    {
      name: "Tartaglia",
      description:
        "No. 11 of The Harbingers, also known as 'Childe.' His name is highly feared on the battlefield.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/3/3a/Character_Tartaglia_Portrait.png/revision/latest/scale-to-width-down/262?cb=20201109083418",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/3/3a/Character_Tartaglia_Portrait.png/revision/latest/scale-to-width-down/262?cb=20201109083418",
      color: "0379fd",
      emoji: "<:tartaglia:843214509760839710>",
      category: "Hydro",
      rarity: "⭐⭐⭐⭐⭐",
      element: "<:Hydro:798483587157983282> Hydro",
      weapon: "Bow",
      nation: "Snezhnaya",
      affiliation: "Fatui",
      specialDish: "A Prize Catch",
      constellation: "Monoceros Caeli",
      birthday: "July 20th",
      ascensionCost: "https://i.imgur.com/JIglNMa.png",
      talentCost: "https://i.imgur.com/i2YtoAQ.png",
      const: "https://i.imgur.com/Gx8Xt0f.png",
      talents: "https://i.imgur.com/ArT6jH4.png",
      passive: "https://i.imgur.com/X1lySSd.png",
    },
  ],
  [
    "bennett",
    {
      name: "Bennett",
      description:
        "A good-natured adventurer from Mondstadt who's unfortunately extremely unlucky.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/7/73/Character_Bennett_Portrait.png/revision/latest/scale-to-width-down/267?cb=20200916170558",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/7/73/Character_Bennett_Portrait.png/revision/latest/scale-to-width-down/267?cb=20200916170558",
      color: "ff4000",
      emoji: "<:bennett:843214508952125470>",
      category: "Pyro",
      rarity: "⭐⭐⭐⭐",
      element: "<:Pyro:798483485832249354> Pyro",
      weapon: "Sword",
      nation: "Mondstadt",
      affiliation: "Adventurers' Guild",
      specialDish: "Teyvat Charred Egg",
      constellation: "Rota Calamitas",
      birthday: "February 29th",
      ascensionCost: "https://i.imgur.com/tsU3tK3.png",
      talentCost: "https://i.imgur.com/T3BZzQu.png",
      const: "https://i.imgur.com/Z4uxEAw.png",
      talents: "https://i.imgur.com/XvtDRCx.png",
      passive: "https://i.imgur.com/xLsfzb7.png",
    },
  ],
  [
    "beidou",
    {
      name: "Beidou",
      description:
        "Captain of her crew, The Crux. She's quite an unbound and forthright woman.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/7/74/Character_Beidou_Portrait.png/revision/latest/scale-to-width-down/237?cb=20200916170732",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/7/74/Character_Beidou_Portrait.png/revision/latest/scale-to-width-down/237?cb=20200916170732",
      color: "e205fd",
      emoji: "<:beidou:843214508793266297>",
      category: "Electro",
      rarity: "⭐⭐⭐⭐",
      element: "<:Electro:798483560205385799> Electro",
      weapon: "Claymore",
      nation: "Liyue",
      affiliation: "Crux Fleet",
      specialDish: "Flash-Fried Filet",
      constellation: "Victor Mare",
      birthday: "February 14th",
      ascensionCost: "https://i.imgur.com/fq6kK7P.png",
      talentCost: "https://i.imgur.com/0nNXa88.png",
      const: "https://i.imgur.com/0mPMvGt.png",
      talents: "https://i.imgur.com/Ns7WE7r.png",
      passive: "https://i.imgur.com/N7vRmrs.png",
    },
  ],
  [
    "barbara",
    {
      name: "Barbara",
      description:
        "Every citizen of Mondstadt adores Barbara. She learned the word 'idol' from a magazine.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/4/4a/Character_Barbara_Portrait.png/revision/latest/scale-to-width-down/253?cb=20200916170845",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/4/4a/Character_Barbara_Portrait.png/revision/latest/scale-to-width-down/253?cb=20200916170845",
      color: "0379fd",
      emoji: "<:barbara:843214508830883860>",
      category: "Hydro",
      rarity: "⭐⭐⭐⭐",
      element: "<:Hydro:798483587157983282> Hydro",
      weapon: "Catalyst",
      nation: "Mondstadt",
      affiliation: "Church of Favonius",
      specialDish: "Spicy Stew",
      constellation: "Crater",
      birthday: "July 5th",
      ascensionCost: "https://i.imgur.com/D8NzZEd.png",
      talentCost: "https://i.imgur.com/pYilGrb.png",
      const: "https://i.imgur.com/EkSbSSp.png",
      talents: "https://i.imgur.com/1CGrcbe.png",
      passive: "https://i.imgur.com/VoMvE5L.png",
    },
  ],
  [
    "amber",
    {
      name: "Amber",
      description:
        "Always energetic and full of life, Amber's the best — albeit only — Outrider of the Knights of Favonius.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/0/00/Character_Amber_Portrait.png/revision/latest/scale-to-width-down/303?cb=20200914160851",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/0/00/Character_Amber_Portrait.png/revision/latest/scale-to-width-down/303?cb=20200914160851",
      color: "ff4000",
      emoji: "<:amber:843214509044269126>",
      category: "Pyro",
      rarity: "⭐⭐⭐⭐",
      element: "<:Pyro:798483485832249354> Pyro",
      weapon: "Bow",
      nation: "Mondstadt",
      affiliation: "Knights of Favonius",
      specialDish: "Outrider's Champion Steak!",
      constellation: "Lepus",
      birthday: "August 10th",
      ascensionCost: "https://i.imgur.com/1tzvBKY.png",
      talentCost: "https://i.imgur.com/h5nlN5P.png",
      const: "https://i.imgur.com/X79shdI.png",
      talents: "https://i.imgur.com/UGkosPd.png",
      passive: "https://i.imgur.com/z4NRfS3.png",
    },
  ],
  [
    "albedo",
    {
      name: "Albedo",
      description:
        "A genius known as the Kreideprinz, he is the Chief Alchemist and Captain of the Investigation Team of the Knights of Favonius.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/2/23/Character_Albedo_Portrait.png/revision/latest/scale-to-width-down/276?cb=20201217140004",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/2/23/Character_Albedo_Portrait.png/revision/latest/scale-to-width-down/276?cb=20201217140004",
      color: "ffc100",
      emoji: "<:albedo:843214508462047353>",
      category: "Geo",
      rarity: "⭐⭐⭐⭐⭐",
      element: "<:Geo:798483630740865044> Geo",
      weapon: "Sword",
      nation: "Mondstadt",
      affiliation: "Knights of Favonius",
      specialDish: "Woodland Dream",
      constellation: "Princeps Cretaceus",
      birthday: "September 13th",
      ascensionCost: "https://i.imgur.com/OEMRiEZ.png",
      talentCost: "https://i.imgur.com/CL5jQrb.png",
      const: "https://i.imgur.com/wfkLYs8.png",
      talents: "https://i.imgur.com/qORumDb.png",
      passive: "https://i.imgur.com/1cVy4ZM.png",
    },
  ],
  [
    "mona",
    {
      name: "Mona",
      description:
        "A mysterious young astrologer who proclaims herself to be 'Astrologist Mona Megistus,' and who possesses abilities to match the title. Erudite, but prideful.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/f/fe/Character_Mona_Portrait.png/revision/latest/scale-to-width-down/287?cb=20200916170444",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/f/fe/Character_Mona_Portrait.png/revision/latest/scale-to-width-down/287?cb=20200916170444",
      color: "0379fd",
      emoji: "<:mona:843214509610500106>",
      category: "Hydro",
      rarity: "⭐⭐⭐⭐⭐",
      element: "<:Hydro:798483587157983282> Hydro",
      weapon: "Catalyst",
      nation: "Mondstadt",
      affiliation: "Hexenzirkel",
      specialDish: "Der Weisheit Letzter Schluss (Life)",
      constellation: "Astrolabos",
      birthday: "August 31st",
      ascensionCost: "https://i.imgur.com/scKdDTR.png",
      talentCost: "https://i.imgur.com/1IG1MVI.png",
      const: "https://i.imgur.com/3h0z1cf.png",
      talents: "https://i.imgur.com/bCrjUrv.png",
      passive: "https://i.imgur.com/PB2im6m.png",
    },
  ],
  [
    "travelergeo",
    {
      name: "Traveler (Geo)",
      description:
        "The Traveler is the playable protagonist of Genshin Impact.\nAt the beginning of the game, both genders are twin siblings from another world, traveling throughout the universe, until an Unknown God ambushed, captured one of them, and sealed their ways of travel, leaving them stranded on Teyvat.\nThey are accompanied by a travel companion named Paimon throughout their journey. ",
      thumbnail:
        "https://genshinimpact.net/wp-content/uploads/2020/09/Character_Traveler_Portrait-768x583.png",
      image:
        "https://genshinimpact.net/wp-content/uploads/2020/09/Character_Traveler_Portrait-768x583.png",
      color: "ffc100",
      emoji: "<:traveler:843214509597392926>",
      category: "Geo",
      rarity: "⭐⭐⭐⭐⭐",
      element: "<:Geo:798483630740865044> Geo",
      weapon: "Sword",
      nation: "Mondstadt",
      affiliation: "Knights of Favonius/Adventurers' Guild",
      specialDish: "None",
      constellation: "Viator (Male)/Viatrix (Female)",
      birthday: "Player's Choice",
      ascensionCost: "https://i.imgur.com/qSPL4Q6.png",
      talentCost: "https://i.imgur.com/EjJV9vt.png",
      const: "https://i.imgur.com/7m1kDDA.png",
      talents: "https://i.imgur.com/RVgdXTp.png",
      passive: "https://i.imgur.com/dXK2T0b.png",
    },
  ],
  [
    "traveleranemo",
    {
      name: "Traveler (Anemo)",
      description:
        "The Traveler is the playable protagonist of Genshin Impact.\nAt the beginning of the game, both genders are twin siblings from another world, traveling throughout the universe, until an Unknown God ambushed, captured one of them, and sealed their ways of travel, leaving them stranded on Teyvat.\nThey are accompanied by a travel companion named Paimon throughout their journey. ",
      thumbnail:
        "https://genshinimpact.net/wp-content/uploads/2020/09/Character_Traveler_Portrait-768x583.png",
      image:
        "https://genshinimpact.net/wp-content/uploads/2020/09/Character_Traveler_Portrait-768x583.png",
      color: "03fd9e",
      emoji: "<:traveler:843214509597392926>",
      category: "Anemo",
      rarity: "⭐⭐⭐⭐⭐",
      element: "<:Anemo:798483595781341194> Anemo",
      weapon: "Sword",
      nation: "Mondstadt",
      affiliation: "Knights of Favonius/Adventurers' Guild",
      specialDish: "None",
      constellation: "Viator (Male)/Viatrix (Female)",
      birthday: "Player's Choice",
      ascensionCost: "https://i.imgur.com/qSPL4Q6.png",
      talentCost: "https://i.imgur.com/EjJV9vt.png",
      const: "https://i.imgur.com/ARSGqlK.png",
      talents: "https://i.imgur.com/vnnJi0h.png",
      passive: "https://i.imgur.com/HwR4kp8.png",
    },
  ],
  [
    "diona",
    {
      name: "Diona",
      description:
        "A young lady who has inherited trace amounts of non-human blood. She is the incredibly popular bartender of the Cat's Tail tavern.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/c/ce/Character_Diona_Portrait.png/revision/latest/scale-to-width-down/281?cb=20201117115533",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/c/ce/Character_Diona_Portrait.png/revision/latest/scale-to-width-down/281?cb=20201117115533",
      color: "00f9ff",
      emoji: "<:diona:843214992958423071>",
      category: "Cryo",
      rarity: "⭐⭐⭐⭐",
      element: "<:Cryo:798483525052530719> Cryo",
      weapon: "Bow",
      nation: "Mondstadt",
      affiliation: "Cat's Tail Tavern",
      specialDish: "Definitely Not Bar Food!",
      constellation: "Feles",
      birthday: "January 18th",
      ascensionCost: "https://i.imgur.com/YzhdzN8.png",
      talentCost: "https://i.imgur.com/IuFHaLq.png",
      const: "https://i.imgur.com/pWaydDQ.png",
      talents: "https://i.imgur.com/3W5Sg10.png",
      passive: "https://i.imgur.com/GHS7VJw.png",
    },
  ],
  [
    "xiao",
    {
      name: "Xiao",
      description:
        "A yaksha adeptus who defends Liyue. Also heralded as the 'Conqueror of Demons' or 'Vigilant Yaksha.'",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/1/1e/Character_Xiao_Portrait.png/revision/latest/scale-to-width-down/310?cb=20200916152108",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/1/1e/Character_Xiao_Portrait.png/revision/latest/scale-to-width-down/310?cb=20200916152108",
      color: "03fd9e",
      emoji: "<:xiao:843214509686128680>",
      category: "Anemo",
      rarity: "⭐⭐⭐⭐⭐",
      element: "<:Anemo:798483595781341194>",
      weapon: "Polearm",
      nation: "Liyue",
      affiliation: "Liyue Adeptus",
      specialDish: "Sweet Dream",
      constellation: "Alatus Nemeseos",
      birthday: "April 17th",
      ascensionCost: "https://i.imgur.com/jx8POJl.png",
      talentCost: "https://i.imgur.com/T9etlaL.png",
      const: "https://i.imgur.com/xdc5sY7.png",
      talents: "https://i.imgur.com/L9jT30H.png",
      passive: "https://i.imgur.com/Swnf9xk.png",
    },
  ],
  [
    "hutao",
    {
      name: "Hu Tao",
      description:
        "The 77th Director of the Wangsheng Funeral Parlor. She took over the business at a rather young age.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/5/50/Character_Hu_Tao_Portrait.png/revision/latest/scale-to-width-down/310?cb=20210227222357",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/5/50/Character_Hu_Tao_Portrait.png/revision/latest/scale-to-width-down/310?cb=20210227222357",
      color: "ff4000",
      emoji: "<:hutao:843215307581554771>",
      category: "Pyro",
      rarity: "⭐⭐⭐⭐⭐",
      element: "<:Pyro:798483485832249354> Pyro",
      weapon: "Polearm",
      nation: "Liyue",
      affiliation: "Wangsheng Funeral Parlor",
      specialDish: "Ghostly March",
      constellation: "Papilio Charontis",
      birthday: "July 15th",
      ascensionCost: "https://i.imgur.com/COxelim.png",
      talentCost: "https://i.imgur.com/7x2XBYZ.png",
      const: "https://i.imgur.com/9bqoF0R.png",
      talents: "https://i.imgur.com/yA0pIP7.png",
      passive: "https://i.imgur.com/H3GPjVr.png",
    },
  ],
  [
    "rosaria",
    {
      name: "Rosaria",
      description:
        "A nun who, outside of her garb, seems nothing at all like a person of the cloth. Known for her sharp, cold words and manner, she often works alone.",
      thumbnail: "https://i.imgur.com/XUkuVIg.png",
      image:
        "https://cdn.discordapp.com/attachments/798566392965103616/820729594503626752/Character_Rosaria_Portrait.png",
      color: "00f9ff",
      emoji: "<:rosaria:820651981210386432>",
      category: "Cryo",
      rarity: "⭐⭐⭐⭐",
      element: "<:Cryo:798483525052530719> Cryo",
      weapon: "Polearm",
      nation: "Mondstadt",
      affiliation: "Church of Favonius",
      specialDish: "Dinner of Judgment",
      constellation: "Spinea Corona",
      birthday: "January 24th",
      ascensionCost: "https://i.imgur.com/8vm4RC8.png",
      talentCost: "https://i.imgur.com/m7YpB5N.png",
      const: "https://i.imgur.com/j2IFZSH.png",
      talents: "https://i.imgur.com/LMlUYfX.png",
      passive: "https://i.imgur.com/12Uc7cX.png",
    },
  ],
  //[
  //  "ayaka",
  //  {
  //    name: "Ayaka",
  //    description:
  //      "",
  //    thumbnail:
  //      "",
  //    image:
  //      "",
  //    color: "00f9ff",
  //    emoji: "<:Ayaka:797753205483372594>",
  //    category: "Cryo",
  //    rarity: "⭐⭐⭐⭐⭐",
  //    element: "<:Cryo:798483525052530719> Cryo",
  //    weapon: "",
  //    nation: "",
  //    affiliation: "",
  //    specialDish: "",
  //    constellation: "",
  //    birthday: "",
  //    ascensionCost: "https://i.imgur.com/3TtXcCv.png",
  //    talentCost: "https://i.imgur.com/kEs3C81.png",
  //    const: "",
  //    talents: "",
  //    passive: "",
  //  },
  //],
  [
    "eula",
    {
      name: "Eula",
      description:
        "The Spindrift Knight, a scion of the old aristocracy, and the Captain of the Knights of Favonius Reconnaissance Company. The reason for which a descendant of the ancient nobles might join the Knights remains a great mystery in Mondstadt to this very day.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/a/ac/Character_Eula_Card.png/revision/latest/scale-to-width-down/310?cb=20210416133528",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/a/ac/Character_Eula_Card.png/revision/latest/scale-to-width-down/310?cb=20210416133528",
      color: "00f9ff",
      emoji: "<:eula:843214509929398293>",
      category: "Cryo",
      rarity: "⭐⭐⭐⭐⭐",
      element: "<:Cryo:798483525052530719> Cryo",
      weapon: "Claymore",
      nation: "Mondstadt",
      affiliation: "Knights of Favonius",
      specialDish: "Stormcrest Pie",
      constellation: "Aphros Delos",
      birthday: "October 25",
      ascensionCost: "https://i.imgur.com/0Iu9hwX.png",
      talentCost: "https://i.imgur.com/iwyrc1i.png",
      const: "https://i.imgur.com/l1YXp8x.png",
      talents: "https://i.imgur.com/G5ZGMou.png",
      passive: "https://i.imgur.com/EMUL1Fz.png",
    },
  ],
  [
    "yanfei",
    {
      name: "Yanfei",
      description:
        "A well-known legal adviser active in Liyue Harbor.\nA brilliant young lady in whose veins runs the blood of an illuminated beast.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/e/e5/Character_Yanfei_Portrait.png/revision/latest/scale-to-width-down/310?cb=20210428164441",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/e/e5/Character_Yanfei_Portrait.png/revision/latest/scale-to-width-down/310?cb=20210428164441",
      color: "ff4000",
      emoji: "<:yanfei:843214509761101854>",
      category: "Pyro",
      rarity: "⭐⭐⭐⭐",
      element: "<:Pyro:798483485832249354> Pyro",
      weapon: "Catalyst",
      nation: "Liyue",
      affiliation: "Liyue Harbor",
      specialDish: "My Way",
      constellation: "Bestia Lustitia",
      birthday: "July 28",
      ascensionCost: "https://i.imgur.com/79ZLN07.png",
      talentCost: "https://i.imgur.com/wGsPrN7.png",
      const: "https://i.imgur.com/sKNO9aX.png",
      talents: "https://i.imgur.com/w4XVdX6.png",
      passive: "https://i.imgur.com/QnB8wSz.png",
    },
  ],
  //[
  //  "yaoyao",
  //  {
  //    name: "Yao Yao",
  //    description:
  //      "",
  //    thumbnail:
  //      "",
  //    image:
  //      "",
  //    color: "",
  //    emoji: "",
  //    category: "",
  //    rarity: "⭐⭐⭐⭐⭐",
  //    element: "",
  //    weapon: "",
  //    nation: "",
  //    affiliation: "",
  //    specialDish: "",
  //    constellation: "",
  //    birthday: "",
  //    ascensionCost: "",
  //    talentCost: "",
  //    const: "",
  //    talents: "",
  //    passive: "",
  //  },
  //],
  [
    "kazuha",
    {
      name: "Kazuha",
      description:
        "A ronin from Inazuma who is currently with Liyue's Crux Fleet. A gentle and carefree soul whose heart hides a great many burdens from the past.",
      thumbnail:
        "https://static.wikia.nocookie.net/gensin-impact/images/b/b5/Character_Kazuha_Card.png/revision/latest/scale-to-width-down/281?cb=20210607100841",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/b/b5/Character_Kazuha_Card.png/revision/latest/scale-to-width-down/281?cb=20210607100841",
      color: "03fd9e",
      emoji: "<:Kazuha:861257160759574558>",
      category: "Anemo",
      rarity: "⭐⭐⭐⭐⭐",
      element: "<:Anemo:798483595781341194>",
      weapon: "Sword",
      nation: "Inazuma",
      affiliation: "The Crux",
      specialDish: "",
      constellation: "Acer Palmatum",
      birthday: "October 29",
      ascensionCost: "https://i.imgur.com/gLf8og5.png",
      talentCost: "",
      const: "https://i.imgur.com/bvGpSGu.png",
      talents: "https://i.imgur.com/lDSWw9Y.png",
      passive: "https://i.imgur.com/dSuUMvn.png",
    },
  ],
  //[
  //  "yae",
  //  {
  //    name: "Yae",
  //    description:
  //      "",
  //    thumbnail:
  //      "",
  //    image:
  //      "",
  //    color: "",
  //    emoji: "",
  //    category: "",
  //    rarity: "⭐⭐⭐⭐⭐",
  //    element: "",
  //    weapon: "",
  //    nation: "",
  //    affiliation: "",
  //    specialDish: "",
  //    constellation: "",
  //    birthday: "",
  //    ascensionCost: "",
  //    talentCost: "",
  //    const: "",
  //    talents: "",
  //    passive: "",
  //  },
  //],
  //[
  //  "yoimiya",
  //  {
  //    name: "Yoimiya",
  //    description:
  //      "",
  //    thumbnail:
  //      "",
  //    image:
  //      "",
  //    color: "",
  //    emoji: "",
  //    category: "",
  //    rarity: "⭐⭐⭐⭐⭐",
  //    element: "",
  //    weapon: "",
  //    nation: "",
  //    affiliation: "",
  //    specialDish: "",
  //    constellation: "",
  //    birthday: "",
  //    ascensionCost: "",
  //    talentCost: "",
  //    const: "",
  //    talents: "",
  //    passive: "",
  //  },
  //],
  //[
  //  "baal",
  //  {
  //    name: "Baal",
  //    description:
  //      "",
  //    thumbnail:
  //      "",
  //    image:
  //      "",
  //    color: "",
  //    emoji: "",
  //    category: "",
  //    rarity: "⭐⭐⭐⭐⭐",
  //    element: "",
  //    weapon: "",
  //    nation: "",
  //    affiliation: "",
  //    specialDish: "",
  //    constellation: "",
  //    birthday: "",
  //    ascensionCost: "",
  //    talentCost: "",
  //    const: "",
  //    talents: "",
  //    passive: "",
  //  },
  //],
  //[
  //  "sayu",
  //  {
  //    name: "Sayu",
  //    description:
  //      "",
  //    thumbnail:
  //      "",
  //    image:
  //      "",
  //    color: "",
  //    emoji: "",
  //    category: "",
  //    rarity: "⭐⭐⭐⭐⭐",
  //    element: "",
  //    weapon: "",
  //    nation: "",
  //    affiliation: "",
  //    specialDish: "",
  //    constellation: "",
  //    birthday: "",
  //    ascensionCost: "",
  //    talentCost: "",
  //    const: "",
  //    talents: "",
  //    passive: "",
  //  },
  //],
  //[
  //  "gorou",
  //  {
  //    name: "Gorou",
  //    description:
  //      "",
  //    thumbnail:
  //      "",
  //    image:
  //      "",
  //    color: "",
  //    emoji: "",
  //    category: "",
  //    rarity: "⭐⭐⭐⭐⭐",
  //    element: "",
  //    weapon: "",
  //    nation: "",
  //    affiliation: "",
  //    specialDish: "",
  //    constellation: "",
  //    birthday: "",
  //    ascensionCost: "",
  //    talentCost: "",
  //    const: "",
  //    talents: "",
  //    passive: "",
  //  },
  //],
  //[
  //  "sara",
  //  {
  //    name: "Sara",
  //    description:
  //      "",
  //    thumbnail:
  //      "",
  //    image:
  //      "",
  //    color: "",
  //    emoji: "",
  //    category: "",
  //    rarity: "⭐⭐⭐⭐⭐",
  //    element: "",
  //    weapon: "",
  //    nation: "",
  //    affiliation: "",
  //    specialDish: "",
  //    constellation: "",
  //    birthday: "",
  //    ascensionCost: "",
  //    talentCost: "",
  //    const: "",
  //    talents: "",
  //    passive: "",
  //  },
  //],
]);
