export const foods = new Map([
    [
      "adeptustemptation",
      {
        name: "Adeptus' Temptation",
        image: "https://static.wikia.nocookie.net/gensin-impact/images/5/5e/Item_Adeptus%27_Temptation.png/revision/latest/scale-to-width-down/310?cb=20201028045529",
        description: "A complex, famous type of Liyue cuisine, in which specially selected ingredients are submerged and slowly bowled into soup stock. The recipe scribbled from memory alone was enough to urge the adepti to once again return to the world of men.",
        color: "RANDOM",
        stars: "⭐⭐⭐⭐⭐",
        recipe: "4x Ham, 3x Crab, 3x Shrimp Meat, 3x Matsutake",
        dishType: "Warrior's Dish",
        proficiency: "25",
        obtainable: "1) Opening a Chest on the floating island above Qingyun Peak.\n2) Reward from the Nine Pillars of Peace quest.",
        effect: "Increases all party members' ATK by **260/316/372** and CRIT Rate by **8/10/12%** for 300s.",
      },
    ],
    [
        "jadeparcels",
        {
          name: "Jade Parcels",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/b/b3/Item_Jade_Parcels.png/revision/latest/scale-to-width-down/247?cb=20201104072417",
          description: "An exquisite-looking dish. The ham's sweetness is locked inside the fresh vegetables, drizzled with a spicy broth. Delicious is an understatement.",
          color: "RANDOM",
          stars: "⭐⭐⭐⭐",
          recipe: "3x Lotus Head, 2x Jueyun Chili, 2x Cabbage, 1x Ham",
          dishType: "Warrior's Dish",
          proficiency: "20",
          obtainable: "Cooking Showdown quest",
          effect: "Increases all party members' ATK by **224/272/320** and CRIT Rate by **6/8/10%** for 300s.",
        },
      ],
      [
        "adeptustemptation",
        {
          name: "goldencrab",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/a/a3/Item_Golden_Crab.png/revision/latest/scale-to-width-down/247?cb=20201226191138",
          description: "A crab dish cooked in the ancient ways. The crab has been chopped into pieces and battered with flour, before being stir-fried till golden and rich with flavor. It is worthy of the word 'gold', whether in terms of appearance or quality.",
          color: "RANDOM",
          stars: "⭐⭐⭐⭐",
          recipe: "5x Bird Egg, 5x Flour, 4x Crab, 2x Salt",
          dishType: "Sage's Dish",
          proficiency: "20",
          obtainable: "Mona's Story Quest",
          effect: "Increases all party members' DEF by **242/261/308** and healing effects by **6/8/10** for 300s.",
        },
      ],
      [
        "moonpie",
        {
          name: "Moon Pie",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/3/38/Item_Moon_Pie.png/revision/latest/scale-to-width-down/247?cb=20201226064510",
          description: "A traditional staple from Mondstadt. Not only is the pickled meat within deeply flavorful, but the meringue has also maintained its sweetness and moisture through the baking process. This dish is not to be missed at any festival in Mondstadt.",
          color: "RANDOM",
          stars: "⭐⭐⭐⭐",
          recipe: "4x Raw Meat, 4x Bird Egg, 3x Butter, 2x Flour",
          dishType: "Sage's Dish",
          proficiency: "20",
          obtainable: "",
          effect: "Increases all party members' Shield Strength by **25/30/35%** and DEF by **165/200/235** for 300s.",
        },
      ],
      [
        "tianshumeat",
        {
          name: "Tianshu Meat",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/f/f3/Item_Tianshu_Meat.png/revision/latest/scale-to-width-down/247?cb=20201226185520",
          description: "A braised meat dish. The cut of meat is a happy medium between lean and fatty, and has been braised to smoking perfection. The ingredients glisten, and are soft but not greasy. Word has it that the Tianshu of a certain generation of the Liyue Qixing invented this dish after much painstaking development.",
          color: "RANDOM",
          stars: "⭐⭐⭐⭐",
          recipe: "4x Raw Meat, 2x Sugar, 1x Qingxin, 1x Matsutake",
          dishType: "Warrior's Dish",
          proficiency: "20",
          obtainable: "From Ms. Yu for reaching Reputation Level 7 in Liyue.",
          effect: "Increases all party members' Physical DMG by **25/35/45%** and CRIT Rate by **6/8/10%** for 300 seconds.",
        },
      ],
      [
        "empty",
        {
          name: "",
          image: "",
          description: "",
          color: "RANDOM",
          stars: "⭐⭐⭐⭐",
          recipe: "",
          dishType: "",
          proficiency: "",
          obtainable: "",
          effect: "",
        },
      ],
      [
        "empty1",
        {
          name: "",
          image: "",
          description: "",
          color: "RANDOM",
          stars: "⭐⭐⭐⭐",
          recipe: "",
          dishType: "",
          proficiency: "",
          obtainable: "",
          effect: "",
        },
      ],
]);