export const foods = new Map([
    [
      "adeptustemptation",
      {
        name: "Adeptus' Temptation",
        image: "https://static.wikia.nocookie.net/gensin-impact/images/5/5e/Item_Adeptus%27_Temptation.png/revision/latest/scale-to-width-down/310?cb=20201028045529",
        description: "A complex, famous type of Liyue cuisine, in which specially selected ingredients are submerged and slowly bowled into soup stock. The recipe scribbled from memory alone was enough to urge the adepti to once again return to the world of men.",
        color: "RANDOM",
        stars: "⭐⭐⭐⭐⭐",
        recipe: "4x Ham, 3x Crab, 3x Shrimp Meat, 3x Matsutake",
        dishType: "Warrior's Dish",
        proficiency: "25",
        obtainable: "1) Opening a Chest on the floating island above Qingyun Peak.\n2) Reward from the Nine Pillars of Peace quest.",
        effect: "Increases all party members' ATK by **260/316/372** and CRIT Rate by **8/10/12%** for 300s.",
      },
    ],
    [
        "jadeparcels",
        {
          name: "Jade Parcels",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/b/b3/Item_Jade_Parcels.png/revision/latest/scale-to-width-down/247?cb=20201104072417",
          description: "An exquisite-looking dish. The ham's sweetness is locked inside the fresh vegetables, drizzled with a spicy broth. Delicious is an understatement.",
          color: "RANDOM",
          stars: "⭐⭐⭐⭐",
          recipe: "3x Lotus Head, 2x Jueyun Chili, 2x Cabbage, 1x Ham",
          dishType: "Warrior's Dish",
          proficiency: "20",
          obtainable: "Cooking Showdown quest",
          effect: "Increases all party members' ATK by **224/272/320** and CRIT Rate by **6/8/10%** for 300s.",
        },
      ],
      [
        "adeptustemptation",
        {
          name: "goldencrab",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/a/a3/Item_Golden_Crab.png/revision/latest/scale-to-width-down/247?cb=20201226191138",
          description: "A crab dish cooked in the ancient ways. The crab has been chopped into pieces and battered with flour, before being stir-fried till golden and rich with flavor. It is worthy of the word 'gold', whether in terms of appearance or quality.",
          color: "RANDOM",
          stars: "⭐⭐⭐⭐",
          recipe: "5x Bird Egg, 5x Flour, 4x Crab, 2x Salt",
          dishType: "Sage's Dish",
          proficiency: "20",
          obtainable: "Mona's Story Quest",
          effect: "Increases all party members' DEF by **242/261/308** and healing effects by **6/8/10** for 300s.",
        },
      ],
      [
        "moonpie",
        {
          name: "Moon Pie",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/3/38/Item_Moon_Pie.png/revision/latest/scale-to-width-down/247?cb=20201226064510",
          description: "A traditional staple from Mondstadt. Not only is the pickled meat within deeply flavorful, but the meringue has also maintained its sweetness and moisture through the baking process. This dish is not to be missed at any festival in Mondstadt.",
          color: "RANDOM",
          stars: "⭐⭐⭐⭐",
          recipe: "4x Raw Meat, 4x Bird Egg, 3x Butter, 2x Flour",
          dishType: "Sage's Dish",
          proficiency: "20",
          obtainable: "From Hertha for reaching Reputation Level 7 in Mondstadt.",
          effect: "Increases all party members' Shield Strength by **25/30/35%** and DEF by **165/200/235** for 300s.",
        },
      ],
      [
        "tianshumeat",
        {
          name: "Tianshu Meat",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/f/f3/Item_Tianshu_Meat.png/revision/latest/scale-to-width-down/247?cb=20201226185520",
          description: "A braised meat dish. The cut of meat is a happy medium between lean and fatty, and has been braised to smoking perfection. The ingredients glisten, and are soft but not greasy. Word has it that the Tianshu of a certain generation of the Liyue Qixing invented this dish after much painstaking development.",
          color: "RANDOM",
          stars: "⭐⭐⭐⭐",
          recipe: "4x Raw Meat, 2x Sugar, 1x Qingxin, 1x Matsutake",
          dishType: "Warrior's Dish",
          proficiency: "20",
          obtainable: "From Ms. Yu for reaching Reputation Level 7 in Liyue.",
          effect: "Increases all party members' Physical DMG by **25/35/45%** and CRIT Rate by **6/8/10%** for 300 seconds.",
        },
      ],
      [
        "crabhamandveggiebake",
        {
          name: "Crab, Ham & Veggie Bake",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/a/af/Item_Crab%2C_Ham_%26_Veggie_Bake.png/revision/latest/scale-to-width-down/247?cb=20201104203154",
          description: "A luxurious bake. Cracks through the golden outer skin reveal a medley of rosy ham and bright vegetables. How tantalizing!",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "1x Crab Roe, 1x Ham, 1x Cream, 1x Cabbage",
          dishType: "Guardian's Dish",
          proficiency: "15",
          obtainable: "Completing a certain version of the commission Food Delivery",
          effect: "Revives the selected character and restores **900/1200/1500** HP.",
        },
      ],
      [
        "holywater",
        {
          name: "Holy Water",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/2/2a/Item_Holy_Water.png/revision/latest/scale-to-width-down/256?cb=20201126234926",
          description: "A bottle of clear, colorless, and contaminant-free liquid. Indistinguishable from ordinary spring water. May or may not be worth putting all of one's hopes into.",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "None",
          dishType: "Guardian's Dish",
          proficiency: "None",
          obtainable: "From Hopkins the Marvelous (located in Springvale, Mondstadt)",
          effect: "Regenerates 1 HP every second for 20 seconds.",
        },
      ],
      [
        "puppy-pawhashbrown",
        {
          name: "Puppy-Paw Hash Brown",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/0/0d/Item_Puppy-Paw_Hash_Brown.png/revision/latest/scale-to-width-down/256?cb=20201210060857",
          description: "Razor's specialty. Carefully shaped to resemble a wolf's paw. You can really feel the effort he has put into trying human cooking.",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "2x Pinecone, 1x Potato, 1x Jam",
          dishType: "Special Guardian's Dish",
          proficiency: "None",
          obtainable: "Cook Mondstadt Hash Brown with Razor.",
          effect: "Restores **40%** of Max HP and an additional **2350** HP.",
        },
      ],
      [
        "wanminrestaurantsboiledfish",
        {
          name: "Wanmin Restaurant's Boiled Fish",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/e/ec/Item_Wanmin_Restaurant%27s_Boiled_Fish.png/revision/latest/scale-to-width-down/256?cb=20201210062546",
          description: "Xiangling's specialty. This is the signature dish of the Wanmin Restaurant, combining Xiangling's heartfelt passion for cuisine. Anyone who tastes it will gain a pure appreciation for gourmet food amid the hearty and addictive blend of flavors.",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "3x Fish, 1x Jueyun Chili, 1x Salt, 1x Violetgrass",
          dishType: "Special Guardian's Dish",
          proficiency: "None",
          obtainable: "Cook Black-Back Perch Stew with Xiangling.",
          effect: "Restores **34%** of Max HP to the selected character and regenerates **980** HP every 5s for 30s.",
        },
      ],
      [
        "onceuponatimeinmondstadt",
        {
          name: "Once Upon a Time in Mondstadt",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/e/e0/Item_%22Once_Upon_a_Time_in_Mondstadt%22.png/revision/latest/scale-to-width-down/256?cb=20201210061034",
          description: "Diluc's specialty. Feast your eyes and then your stomach upon this delicacy as the soft ribs melt in your mouth. Who knew Dliuc was able to cook this well?",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "3x Meat, 3x Potato, 1x Small Lamp Grass, 1x Cheese",
          dishType: "Special Warrior's Dish",
          proficiency: "None",
          obtainable: "Cook Pile 'Em Up with Diluc.",
          effect: "Increases all party members' CRIT Rate by **20%** and CRIT DMG by **20%** for 300s.",
        },
      ],
      [
        "dieheiligesinfonie",
        {
          name: "Die Heilige Sinfonie",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/c/c3/Item_Die_Heilige_Sinfonie.png/revision/latest/scale-to-width-down/256?cb=20201210061227",
          description: "Fischl's specialty. The exquisite presentation doth seem to communicate some incomprehensible enigma. When partaking, if one were to gaze upon Fischl, one might see her expectant gaze peek though the gaps of her fingers, which she is using to cover half her face... Is this also part of the mystery?",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "1x Ham, 1x Bacon, 1x Sausage, 1x Mint",
          dishType: "Special Warrior's Dish",
          proficiency: "None",
          obtainable: "Cook Cold Cut Platter with Fischl.",
          effect: "Increases all party members' Physical DMG by **55%** for 300s.",
        },
      ],
      [
        "invigoratingpizza",
        {
          name: "Invigorating Pizza",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/5/5f/Item_Invigorating_Pizza.png/revision/latest/scale-to-width-down/256?cb=20201210061826",
          description: "Jean's specialty. This pizza almost seems more art than food. Just one slice is enough to have you raring to go. Is this what keeps Jean working so hard?",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "4x Mushroom, 3x Flour, 2x Cabbage, 1x Cheese",
          dishType: "Special Guardian's Dish",
          proficiency: "None",
          obtainable: "Cook Mushroom Pizza with Jean",
          effect: "Restores **34%** of Max HP to the selected character and regenerates **980** HP every 5s for 30s.",
        },
      ],
      [
        "abuoyantbreeze",
        {
          name: "A Buoyant Breeze",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/8/8e/Item_A_Buoyant_Breeze.png/revision/latest/scale-to-width-down/256?cb=20201210060105",
          description: "Venti's specialty. Other than the Cecilia flowers used for decoration, the ingredients are no different from normal. But if you taste it carefully, you can taste the flavor of 'a wind that brings hope and tiny twists of fate.' Perhaps...this is exactly what he wants.",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "4x Carrot, 4x Potato, 4x Onion",
          dishType: "Special Adventurer's Dish",
          proficiency: "None",
          obtainable: "Cook Barbatos Ratatouille with Venti.",
          effect: "Decreases all party members' gliding and sprinting Stamina consumption by **25%** for 1800s.",
        },
      ],
      [
        "notomorrow",
        {
          name: "No Tomorrow",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/1/12/Item_No_Tomorrow.png/revision/latest/scale-to-width-down/256?cb=20201210062627",
          description: "Qiqi's specialty. The neat rows of ingredients seem at once exotic and delicious, and Baizhu says that Qiqi has spent a long time creating this dish. Still, once one considers that Qiqi has no sense of taste, just putting chopsticks to the food is going to take some courage.",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "3x Meat, 3x Fish, 3x Rice, 1x Tofu",
          dishType: "Special Warrior's Dish",
          proficiency: "None",
          obtainable: "Cook Come and Get It with Qiqi.",
          effect: "Increases all party members' CRIT Rate by **20%** and CRIT DMG by **20%** for 300s.",
        },
      ],
      [
        "nutritiousmeal",
        {
          name: "Nutritious Meal (V. 593)",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/5/51/Item_Nutritious_Meal_%28V._593%29.png/revision/latest/scale-to-width-down/256?cb=20201210062741",
          description: "Sucrose's specialty. It looks like some strange alchemical product at first, but Sucrose insists that it is a healthy and nutritious meal, the result of many experiments and painstaking improvements. Its healthy green color comes from a mix of cream and natural vegetable juices... Wait, vegetable juices?",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "1x Crab Roe, 1x Ham, 1x Cream, 1x Cabbage",
          dishType: "Special Guardian's Dish",
          proficiency: "None",
          obtainable: "Cook Crab, Ham & Veggie Bake with Sucrose.",
          effect: "Revives a character and restores **20%** of Max HP and an additional **1500** HP.",
        },
      ],
      [
        "black-backperchstew",
        {
          name: "Black-Back Perch Stew",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/3/31/Item_Black-Back_Perch_Stew.png/revision/latest/scale-to-width-down/247?cb=20201104211134",
          description: "A poached fish dish. The fresh and tasty fish fillets are tender and juicy. The secret to this recipe is adding powdered Violetgrass into the heated oil to give the dish that aromatic scent. It's spicy, but not too spicy.",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "3x Fish, 1x Jueyun Chili, 1x Salt, 1x Violetgrass",
          dishType: "Guardian's Dish",
          proficiency: "15",
          obtainable: "Chef Mao in Wanmin Restaurant (located in Liyue Harbor, Liyue) for 5,000 Mora after reaching Adventure Rank 30.",
          effect: "Restores **28%** of Max HP to the selected character and regenerates **620** HP every 5s for 30s.",
        },
      ],
      [
        "callalilyseafoodsoup",
        {
          name: "Calla Lily Seafood Soup",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/4/4e/Item_Calla_Lily_Seafood_Soup.png/revision/latest/scale-to-width-down/247?cb=20201104081556",
          description: "A balanced combination of seafood. The delicacy of crab and mint make for a clear soup, and the calla lily brings it a refreshing taste.",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "4x Crab, 1x Calla Lily, 2x Mint",
          dishType: "Sage's Dish",
          proficiency: "15",
          obtainable: "From Sara in Good Hunter (located in Mondstadt (City)) for 5,000 Mora after reaching Adventure Rank 30.",
          effect: "Increases all party members' DEF by **200** for 300s.",
        },
      ],
      [
        "coldcutplatter",
        {
          name: "Cold Cut Platter",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/1/16/Item_Cold_Cut_Platter.png/revision/latest/scale-to-width-down/247?cb=20201104201821",
          description: "A plate of cold cut meat. An equal balance of bacon, ham and sausage keeps everyone happy.",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "1x Ham, 1x Bacon, 1x Sausage, 1x Mint",
          dishType: "Warrior's Dish",
          proficiency: "15",
          obtainable: "Completing the domain Eagle's Gate after reaching Adventure Rank 21.",
          effect: "Increases all party members' Physical DMG by **30%** for 300s.",
        },
      ],
      [
        "mondstadthashbrown",
        {
          name: "Mondstadt Hash Brown",
          image: "https://static.wikia.nocookie.net/gensin-impact/images/e/e8/Item_Mondstadt_Hash_Brown.png/revision/latest/scale-to-width-down/247?cb=20201104194110",
          description: "A fried cake of mashed potatoes. A little bit of pinecone helps give it a nice crunch, and great with a bit of jam. Loved by people of all ages.",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "2x Pinecone, 1x Potato, 1x Jam",
          dishType: "Guardian's Dish",
          proficiency: "15",
          obtainable: "Completing the domain Temple of the Wolf after reaching Adventure Rank 15.",
          effect: "Restores **32%** of Max HP and an additional **1250** HP.",
        },
      ],
      [
        "empty1",
        {
          name: "",
          image: "",
          description: "",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "",
          dishType: "",
          proficiency: "",
          obtainable: "",
          effect: "",
        },
      ],
      [
        "empty2",
        {
          name: "",
          image: "",
          description: "",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "",
          dishType: "",
          proficiency: "",
          obtainable: "",
          effect: "",
        },
      ],
      [
        "empty3",
        {
          name: "",
          image: "",
          description: "",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "",
          dishType: "",
          proficiency: "",
          obtainable: "",
          effect: "",
        },
      ],
      [
        "empty4",
        {
          name: "",
          image: "",
          description: "",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "",
          dishType: "",
          proficiency: "",
          obtainable: "",
          effect: "",
        },
      ],
      [
        "empty5",
        {
          name: "",
          image: "",
          description: "",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "",
          dishType: "",
          proficiency: "",
          obtainable: "",
          effect: "",
        },
      ],
      [
        "empty6",
        {
          name: "",
          image: "",
          description: "",
          color: "RANDOM",
          stars: "⭐⭐⭐",
          recipe: "",
          dishType: "",
          proficiency: "",
          obtainable: "",
          effect: "",
        },
      ],
]);