export const weapons = new Map([
  [  
    "coolsteel",
    {
      name: "Cool Steel",
      description: "A reliable steel-forged weapon that serves as a testament to the great adventures of its old master.",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/9/9c/Weapon_Cool_Steel.png/revision/latest/scale-to-width-down/256?cb=20201119233444",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐",
      baseAttack: "39",
      secondaryStat: "ATK%",
      secondaryStatValue: "7,7%",
      specialAbility: "Bane of Water and Ice",
      moreInfo: "",
      refinement: "Increases DMG against opponents affected by Hydro or Cryo by **12/15/18/21/24%**.",
    }
  ],
  [
    "skyridersword",
    {
      name: "Skyrider Sword",
      description: "A reliable steel sword. The legendary Skyrider once tried to ride it as a flying sword...",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/3/34/Weapon_Skyrider_Sword.png/revision/latest/scale-to-width-down/256?cb=20201116035206",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐",
      baseAttack: "38",
      secondaryStat: "Energy Recharge",
      secondaryStatValue: "11,3%",
      specialAbility: "Determination",
      moreInfo: "https://genshin-impact.fandom.com/wiki/Skyrider_Sword",
      refinement: "Using an Elemental Burst grants a **12/15/18/21/24%** increase in ATK and Movement SPD for 15s.",
    },
  ],
  [
    "filletblade",
    {
      name: "Fillet Blade",
      description: "A sharp filleting knife. The blade is long, thin, and incredibly sharp.",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/f/f7/Weapon_Fillet_Blade.png/revision/latest/scale-to-width-down/256?cb=20201116033941",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐",
      baseAttack: "39",
      secondaryStat: "ATK%",
      secondaryStatValue: "7,7%",
      specialAbility: "Gash",
      moreInfo: "https://genshin-impact.fandom.com/wiki/Fillet_Blade",
      refinement: "On hit, has 50% chance to deal **240/280/320/360/400%** ATK DMG to a single enemy. Can only occur once every **15/14/13/12/11s**.",
    },
  ],
  [
    "travelershandysword",
    {
      name: "Traveler's Handy Sword",
      description: "A handy steel sword which contains scissors, a magnifying glass, tinder, and other useful items in its sheath.",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/c/c9/Weapon_Traveler%27s_Handy_Sword.png/revision/latest?cb=20201116035456",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐",
      baseAttack: "40",
      secondaryStat: "DEF",
      secondaryStatValue: "6,4%",
      specialAbility: "Journey",
      moreInfo: "https://genshin-impact.fandom.com/wiki/Traveler%27s_Handy_Sword",
      refinement: "Each Elemental Orb or Particle collected restores **1/1,25/1,5/1,75/2%** HP.",
    },
  ],
  [
    "harbingerofdawn",
    {
      name: "Harbinger of Dawn",
      description: "A sword that once shone like the sun. The wielder of this sword will be blessed with a 'feel-good' buff. The reflective material on the blade has long worn off.",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/2/23/Weapon_Harbinger_of_Dawn.png/revision/latest/scale-to-width-down/256?cb=20201119233056",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐",
      baseAttack: "39",
      secondaryStat: "CRIT DMG",
      secondaryStatValue: "10,2%",
      specialAbility: "Vigorous",
      moreInfo: "",
      refinement: "When HP is above 90%, increases CRIT Rate by **14/17.5/21/24,5/28%**.",
    },
  ],
  [
    "darkironsword",
    {
      name: "Dark Iron Sword",
      description: "A perfectly ordinary iron sword, just slightly darker than most.",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/3/3a/Weapon_Dark_Iron_Sword.png/revision/latest/scale-to-width-down/256?cb=20201119235556",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐",
      baseAttack: "39",
      secondaryStat: "Elemental Mastery",
      secondaryStatValue: "31",
      specialAbility: "Overloaded",
      moreInfo: "https://genshin-impact.fandom.com/wiki/Dark_Iron_Sword",
      refinement: "Upon causing an Overloaded, Superconduct, Electro-Charged, or an Electro-infused Swirl reaction, ATK is increased by **20/25/30/35/40%** for 12s.",
    },
  ],
  [
    "blackclifflongsword",
    {
      name: "Blackcliff Longsword",
      description: "A sword made of blackstone. It has a dark crimson glow on its black blade.",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/6/6f/Weapon_Blackcliff_Longsword.png/revision/latest?cb=20201116033216",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐⭐",
      baseAttack: "44",
      secondaryStat: "CRIT DMG",
      secondaryStatValue: "8%",
      specialAbility: "Press the Advantage",
      moreInfo: "https://genshin-impact.fandom.com/wiki/Blackcliff_Longsword",
      refinement: "After defeating an opponent, ATK is increased by **12/15/18/21/24%** for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
    },
  ],
  [
    "sacrificialsword",
    {
      name: "Sacrificial Sword",
      description: "A ceremonial sword that has become petrified over time. The trinkets on it are still visible. It grants the wielder the power to withstand the winds of time.",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/a/a0/Weapon_Sacrificial_Sword.png/revision/latest?cb=20201120010840",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐⭐",
      baseAttack: "41",
      secondaryStat: "Energy Recharge",
      secondaryStatValue: "13,3%",
      specialAbility: "Composed",
      moreInfo: "https://genshin-impact.fandom.com/wiki/Sacrificial_Sword",
      refinement: "After damaging an opponent with an Elemental Skill, the skill has a **40/50/60/70/80%** chance to end its own CD. Can only occur once every **30/26/22/19/16s**.",
    },
  ],
  [
    "swordofdescension",
    {
      name: "Sword of Descension",
      description: "\n**PS4 sword only!**\n\nA sword of unique craftsmanship. It does not appear to belong to this world.",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/1/17/Weapon_Sword_of_Descension.png/revision/latest/scale-to-width-down/256?cb=20201116035338",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐⭐",
      baseAttack: "39",
      secondaryStat: "ATK%",
      secondaryStatValue: "7,7%",
      specialAbility: "Descension",
      moreInfo: "https://genshin-impact.fandom.com/wiki/Sword_of_Descension",
      refinement: "Hitting enemies with Normal or Charged Attacks grants a 50% chance to deal 200% ATK as DMG in a small AoE. This effect can only occur once every 10s. Additionally, if the Traveler equips the Sword of Descension, their ATK is increased by 66."
    },
  ],

 // CBT CONTENT **TODO**
 // [
 //   "thealleyflash",
 //   {
 //     name: "The Alley Flash",
 //     description: "",
 //     thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/8/83/Weapon_The_Alley_Flash.png/revision/latest/scale-to-width-down/194?cb=20201016011557",
 //     color: "RANDOM",
 //     category: "Sword",
 //     stars: "⭐⭐⭐⭐",
 //     baseAttack: "44",
 //     secondaryStat: "CRIT Rate",
 //     secondaryStatValue: "4%",
 //     specialAbility: "Itinerant Hero",
 //     moreInfo: "",
 //     refinementLevel: "Continuously sprinting for at least 1s increases ATK by 28% for 6s. This effect cannot stack."
 //   },
 // ],
  [
    "favoniussword",
    {
      name: "Favonius Sword",
      description: "A standard-issue longsword of the Knights of Favonius. When you're armed with this agile and sharp weapon, channeling the power of the elements has never been so easy!",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/9/90/Weapon_Favonius_Sword.png/revision/latest?cb=20201116033811",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐⭐",
      baseAttack: "41",
      secondaryStat: "Energy Recharge",
      secondaryStatValue: "13,3%",
      specialAbility: "Windfall",
      moreInfo: "https://genshin-impact.fandom.com/wiki/Favonius_Sword",
      refinementLevel: "CRIT hits have a **60/70/80/90/100%** chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every **12/10,5/9/7,5/6s**.",
    },
  ],
  [
    "theblacksword",
    {
      name: "The Black Sword",
      description: "A pitch-black longsword that thirsts for violence and conflict. It is said that this weapon can cause its user to become drunk on the red wine of slaughter.",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/c/cf/Weapon_The_Black_Sword.png/revision/latest/scale-to-width-down/256?cb=20201116035352",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐⭐",
      baseAttack: "42",
      secondaryStat: "CRIT Rate",
      secondaryStatValue: "6%",
      specialAbility: "Justice",
      moreInfo: "https://genshin-impact.fandom.com/wiki/The_Black_Sword",
      refinement: "Increases DMG dealt by Normal and Charged Attacks by **20/25/30/35/40%**. Additionally, regenerates **60/70/80/90/100%** of ATK as HP when Normal and Charged Attacks score a CRIT Hit. This effect can occur once every 5s.",
    },
  ],
  [
    "theflute",
    {
      name: "The Flute",
      description: "Beneath its rusty exterior is a lavishly decorated thin blade. It swings as swiftly as the wind.",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/6/63/Weapon_The_Flute.png/revision/latest?cb=20201119203316",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐⭐",
      baseAttack: "42",
      secondaryStat: "ATK%",
      secondaryStatValue: "9%",
      specialAbility: "Chord",
      moreInfo: "https://genshin-impact.fandom.com/wiki/The_Flute",
      refinement: "Normal or Charged Attacks grant a Harmonic on hits. Gaining 5 Harmonics triggers the power of music and deals **100/125/150/175/200%** ATK DMG to surrounding enemies. Harmonics last up to 30s, and a maximum of 1 can be gained every 0.5s.",
    },
  ],
  [
    "royallongsword",
    {
      name: "Royal Longsword",
      description: "An old longsword that belonged to the erstwhile rulers of Mondstadt. Exquisitely crafted, the carvings and embellishments testify to the stature of its owner.",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/c/cd/Weapon_Royal_Longsword.png/revision/latest?cb=20201116034952",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐⭐",
      baseAttack: "42",
      secondaryStat: "ATK%",
      secondaryStatValue: "9%",
      specialAbility: "Focus",
      moreInfo: "https://genshin-impact.fandom.com/wiki/Royal_Longsword",
      refinement: "Upon dealing damage to an opponent, increases CRIT Rate by **8/10/12/14/16%**. Max 5 stacks. A CRIT hit removes all existing stacks.",
    },
  ],
  [
    "prototyperancour",
    {
      name: "Prototype Rancour",
      description: "An ancient longsword discovered in the Blackcliff Forge that cuts through rocks like a hot knife through butter.",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/e/ef/Weapon_Prototype_Rancour.png/revision/latest/scale-to-width-down/256?cb=20201116034823",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐⭐",
      baseAttack: "44",
      secondaryStat: "Physical DMG Bonus",
      secondaryStatValue: "7,5%",
      specialAbility: "Smashed Stone",
      moreInfo: "https://genshin-impact.fandom.com/wiki/Prototype_Rancour",
      refinement: "On hit, Normal or Charged Attacks increase ATK and DEF by **4/5/6/7/8%** for 6s. Max 4 stacks. Can only occur once every 0.3s.",
    },
  ],
  [
    "ironsting",
    {
      name: "Iron Sting",
      description: "An exotic long-bladed rapier that somehow found its way into Liyue via foreign traders. It is light, agile, and sharp.",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/3/35/Weapon_Iron_Sting.png/revision/latest/scale-to-width-down/256?cb=20201116034058",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐⭐",
      baseAttack: "42",
      secondaryStat: "Elemental Mastery",
      secondaryStatValue: "36",
      specialAbility: "Infusion Stringer",
      moreInfo: "https://genshin-impact.fandom.com/wiki/Iron_Sting",
      refinement: "Dealing Elemental DMG increases all DMG by **6/7,5/9/10,5/12%** for 6s. Max 2 stacks. Can only occur once every 1s.",
    },
  ],
  [
    "festeringdesire",
    {
      name: "Festering Desire",
      description: " creepy straight sword that almost seems to yearn for life. It drips with a shriveling venom that could even corrupt a mighty dragon.",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/7/70/Weapon_Festering_Desire.png/revision/latest/scale-to-width-down/256?cb=20201223042935",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐⭐",
      baseAttack: "42",
      secondaryStat: "Energy Recharge",
      secondaryStatValue: "10%",
      specialAbility: "Undying Admiration",
      moreInfo: "https://genshin-impact.fandom.com/wiki/Festering_Desire",
      refinement: "Increases Elemental Skill DMG by **16/20/24/28/32%** and Elemental Skill CRIT Rate by **6/7,5/9/10,5/12%**.",
    },
  ],
  [
    "summitshaper",
    {
      name: "Summit Shaper",
      description: "A symbol of a legendary pact, this sharp blade once cut off the peak of a mountain.",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/c/ca/Weapon_Summit_Shaper.png/revision/latest/scale-to-width-down/256?cb=20201223042936",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐⭐⭐",
      baseAttack: "46",
      secondaryStat: "ATK%",
      secondaryStatValue: "10,8%",
      specialAbility: "Golden Majesty",
      moreInfo: "https://genshin-impact.fandom.com/wiki/Summit_Shaper",
      refinement: "Increases Shield Strength by **20/25/30/35/40%**. Scoring hits on opponents increases ATK by **4/5/6/7/8%** for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield, this ATK increase effect is increased by 100%.",
    },
  ],
  [
    "aquilafavonia",
    {
      name: "Aquila Favonia",
      description: "The sword of the Knights of Favonius. Millennia later, it still calls on the winds of swift justice to vanquish all evil—just like the last heroine who wielded it.",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/6/6a/Weapon_Aquila_Favonia.png/revision/latest?cb=20201120002750",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐⭐⭐",
      baseAttack: "48",
      secondaryStat: "Physical DMG Bonus",
      secondaryStatValue: "9%",
      specialAbility: "Falcon's Defiance",
      moreInfo: "https://genshin-impact.fandom.com/wiki/Aquila_Favonia",
      refinement: "ATK is increased by **20/25/30/35/40%**. Triggers on taking DMG: the soul of the Falcon of the West awakens, holding the banner of the resistance aloft, regenerating HP equal to **100/115/130/145/160%** of ATK and dealing **200/230/260/290/320%** of ATK as DMG to surrounding opponents. This effect can only occur once every 15s.",
    },
  ],
  [
    "skywardblade",
    {
      name: "Skyward Blade",
      description: "The sword of a knight that symbolizes the restored honor of Dvalin. The blessings of the Anemo Archon rest on the fuller of the blade, imbuing the sword with the powers of the sky and the wind.",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/0/03/Weapon_Skyward_Blade.png/revision/latest?cb=20201116035239",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐⭐⭐",
      baseAttack: "46",
      secondaryStat: "Energy Recharge",
      secondaryStatValue: "12%",
      specialAbility: "Sky-Piercing Fang",
      moreInfo: "https://genshin-impact.fandom.com/wiki/Skyward_Blade",
      refinement: "Crit Rate increased by **4/5/6/7/8%**. Gains Skypiercing Might upon using Elemental Burst: Increases Movement SPD by 10%, increases ATK SPD by 10%, and increases the DMG of Normal and Charged Attack hits by **20/25/30/35/40%** for 12s.",
    },
  ],
  [
    "lionsroar",
    {
      name: "Lion's Roar",
      description: "A sharp blade with extravagant carvings that somehow does not compromise on durability and sharpness. It roars like a lion as it cuts through the air.",
      thumbnail: "https://static.wikia.nocookie.net/gensin-impact/images/e/e6/Weapon_Lion%27s_Roar.png/revision/latest?cb=20201119232745",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐⭐⭐",
      baseAttack: "42",
      secondaryStat: "ATK%",
      secondaryStatValue: "9%",
      specialAbility: "Bane of Fire and Thunder",
      moreInfo: "https://genshin-impact.fandom.com/wiki/Lion%27s_Roar",
      refinement: "Increases DMG against enemies affected by Pyro or Electro by **20/24/28/32/36%**.",
    },
  ],
  [
    "empty1",
    {
      name: "",
      description: "",
      thumbnail: "",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐⭐⭐",
      baseAttack: "",
      secondaryStat: "",
      secondaryStatValue: "",
      specialAbility: "",
      moreInfo: "",
      refinement: "",
    },
  ],
  [
    "empty2",
    {
      name: "",
      description: "",
      thumbnail: "",
      color: "RANDOM",
      category: "Sword",
      stars: "⭐⭐⭐⭐⭐",
      baseAttack: "",
      secondaryStat: "",
      secondaryStatValue: "",
      specialAbility: "",
      moreInfo: "",
      refinement: "",
    },
  ],
]);
